//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePriceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class product1
    {
        public int id { get; set; }
        public byte[] product { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string created_by { get; set; }
        public string modified_by { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<System.Guid> store_id { get; set; }
        public Nullable<bool> active { get; set; }
        public string product_xml { get; set; }
    }
}
