//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePriceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class quote1
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public decimal total { get; set; }
        public string user { get; set; }
        public string product_name { get; set; }
        public short revisions { get; set; }
        public byte[] quote { get; set; }
        public string item { get; set; }
        public Nullable<int> revision { get; set; }
        public Nullable<System.Guid> store_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string quote_xml { get; set; }
    }
}
