//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePriceSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_accounts
    {
        public System.Guid id { get; set; }
        public string user { get; set; }
        public string pwd { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string company { get; set; }
        public byte[] photo { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> store_id { get; set; }
        public Nullable<short> role { get; set; }
    }
}
