//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePriceSystem
{
    using System;
  
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Infrastructure;
    
    public partial class ops_inhouseEntities : DbContext
    {
        public ops_inhouseEntities()
            : base(GetOptions("Data Source=database-1.cg9byk00fimn.us-east-1.rds.amazonaws.com;Initial Catalog=ops_inhouse;User ID=admin;Password=o4Pk2rnwvroz1yij2BP6"))
        {
        }
        private static DbContextOptions GetOptions(string connectionString)
        {
            return SqlServerDbContextOptionsExtensions.UseSqlServer(new DbContextOptionsBuilder(), connectionString).Options;
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<product1> products { get; set; }
        public virtual DbSet<quote1> quotes { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<store> stores { get; set; }
        public virtual DbSet<user_accounts> user_accounts { get; set; }
    }
}
